version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      APP_SECRET: change_me
      DATABASE_URL: "postgresql://app:change_me@db:5432/app?serverVersion=16&charset=utf8"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: change_me
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
